import { StyleSheet } from 'react-native';

const CARD_WIDTH = 120;

const createStyles = (colors: any) => StyleSheet.create({
  container: {
    width: CARD_WIDTH,
    height: CARD_WIDTH * 1.6,
    backgroundColor: colors.surface,
    borderRadius: 8,
    marginRight: 8,
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: colors.border,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  imageContainer: {
    width: '100%',
    height: CARD_WIDTH * 0.9,
    backgroundColor: colors.border,
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  placeholderContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.border,
  },
  forfaitBadge: {
    position: 'absolute',
    top: 3,
    left: 3,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderRadius: 6,
    gap: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
    maxWidth: '45%',
  },
  forfaitText: {
    fontSize: 6,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  priceBadge: {
    position: 'absolute',
    top: 3,
    right: 3,
    backgroundColor: '#EA580C',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    maxWidth: '50%',
  },
  priceText: {
    color: '#FFF',
    fontSize: 7,
    fontWeight: '700',
    flexShrink: 1,
  },
  favoriteButton: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 26,
    height: 26,
    borderRadius: 13,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  contentContainer: {
    padding: 8,
    flex: 1,
    justifyContent: 'space-between',
  },
  name: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 4,
    height: 32,
    lineHeight: 16,
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    flex: 1,
    overflow: 'hidden',
    marginRight: 4,
  },
  cityText: {
    fontSize: 10,
    color: colors.textSecondary,
    flex: 1,
    marginLeft: 2,
  },
  viewsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  viewsText: {
    fontSize: 9,
    color: colors.textSecondary,
  },
});

export default createStyles;